
= Getting started with GitHub pull request reviews
:toc: left
:toclevels: 3

:toc!:

[lead]
This guide describes the steps to open a pull request and request a review of changed files using the GitHub UI.  

== Introduction to GitHub pull requests

A GitHub pull request is a request to merge changes from one branch into another branch. The pull request build verifies that the branches are compatible for merging. After the pull request has finished building, a user with merging permissions can begin the merge. 

Before a branch is merged, you can request a review of the changed files from specific GitHub users or groups. To request a review of your files, open a pull request and assign the GitHub user or group that needs to approve the changes. 

== Opening a pull request

Before you can assign a reviewer, you must open a pull request for the branch that contains the changed files against the branch that you want your changes to be merged with. 

.Prerequisites

* You must have the required permissions to open a pull request in the chosen repository. 
* You must know the name of the base branch that you want to merge your changes into. 


.Steps 

. Navigate to the GitHub repository for your branch. 

. Go to the *Pull requests* tab and select *New pull request*. 
 
. Identify the branches you want to compare and merge. 
+
Set the *base:* and *compare:* branches by selecting the branch name from the drop-down list. 
+
[%header,cols="1,1"]
|===
| Branch  | Selection
|*base:* 
|The branch that you want to merge your changes into. 
|*compare:*
|The branch that contains your changes.  

|===
+
IMPORTANT: You must make sure that you have selected the correct branch names. 

. At this stage, you can perform a final check of your changes by scrolling to the end of the page to view the changed files. 
+ 
* Additions are in green. 
+
* Deletions are in red.

. Select *Open pull request* to begin building the pull request.     
+
NOTE: Pull request build times vary depending on the repository. You do not have to wait for the pull request to finish building to request a review.  

== Requesting a review
Assign a reviewer to the pull request to request review and approval of the changed files. You can assign any user or group that has the required permissions to a pull request. 

.Prerequisites

* The designated reviewer or group must have a GitHub account and the required permissions for the repository. Learn more about GitHub permissions.

.Steps

. Navigate to the repository that contains the pull request.
. Go to the *Pull requests* tab and select the pull request that requires a review.
. Assign the pull request.
+
Under *Reviewers* on the right side of the screen, enter the GitHub user or group name into the text box. 
+
If the reviewer has the correct permissions, the user or group name should appear in the drop-down list. 
+
NOTE: A green tick should appear next to the name on the list after it has been selected. 
+
If necessary, you can assign multiple users or groups to a pull request.

. Confirm that the reviewer received your request. 
+
Although reviewers automatically recieve an email notfiying them of the request, you should confirm that they are aware of the requested review. 
	








