
= Getting started with GitHub pull request reviews
:toc: left
:toclevels: 3

:toc!:

[lead]
This foundational guide describes the steps to open a pull request and request a review of changed files using the GitHub UI.  

== Introduction to GitHub pull request reviews

A GitHub pull request is a request to merge changes from one branch to another. A successful pull request build verifies that the branches are compatible for merging.  

By default, any GitHub user with read access for a repository can review and request changes on open pull requests in that repository. However, organizations and repository administrators can limit and control who can request changes on open pull requests. Refer to your organization or repository adminstrator for guidance on specific questions about your repository settings. 

To request a review from a specific GitHub user or group, you can assign them as a reviewer on the pull request.   

link:https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews[Learn more about pull request reviews^].

== Opening a pull request

Before you can assign a reviewer, you must open a pull request between the branch that contains the changed files and the base branch.

.Prerequisites

* You must have the required permissions to open a pull request in the repository. 
* You must know the name of the base branch that you want to create the pull request against. 


.Steps 

. Navigate to the GitHub repository for your branch. 

. Go to the *Pull requests* tab and select *New pull request*. 
 
. Identify the branches that you want to merge. 
+
Set the *base:* and *compare:* branches by selecting the branch name from the drop-down list. 
+
[%header,cols="1,1"]
|===
| Branch  | Selection
|*base:* 
|The branch that you want to merge your changes into. 
|*compare:*
|The branch that contains your changes.  

|===
+
IMPORTANT: Make sure that you select the correct branch names. 

. At this stage, perform a final check of your changes by scrolling to the end of the page to view the files changed. 
+ 
* Additions are in green. 
+
* Deletions are in red.

. Select *Open pull request* to begin building the pull request.     
+
NOTE: Pull request build times vary depending on the repository. You do not have to wait for the pull request to finish building to request a review.  

== Requesting a review

You can assign a specific GitHub user or group to the pull request to request review and approval of the changed files. 

.Prerequisites
 
* The reviewer must have a GitHub account and the required permissions for the repository. 
* You must know the GitHub user or group name of the reviewer you want to assign.
* You can only assign a reviewer after the pull request is opened. 

.Steps

. Navigate to the repository that contains the pull request. 

. Go to the *Pull requests* tab and select the pull request that requires a review.
. Assign the pull request.
+
Under *Reviewers* on the right side of the screen, enter the GitHub user or group name into the text box. 
+
If the reviewer has the correct permissions, the user or group name should appear in the drop-down list. 
+
A green tick appears next to the name on the list when it is selected. After the reviewer is successfully assigned, their user or group name is listed under *Reviewers*. 
+
NOTE: Depending on your requirements, you can assign multiple reviewers to the pull request.

. Confirm that the reviewer received your request. 
+
Although reviewers automatically receive an email notfiying them of the request, you should confirm that they are aware of the requested review. 
	








