
= Get started with GitHub pull request reviews
:toc: left
:toclevels: 3

:toc!:

[lead]
This beginners guide describes the steps to open and review GitHub pull requests.  

== Introduction to GitHub pull requests

To request a review of your files before merging, open a pull request and assign the GitHub user who needs to approve the changes. If you are assigned a pull request to review, you can leave feedback, request changes, and approve the request using the GitHub GUI.

== Opening a PR

Before you can assign a reviewer, you must open a pull request for the branch that contains the changed files against the branch that you want your changes to be merged with. 

.Prerequisites

* You must have the required permissions to open a pull request in the chosen repository. 
* Before opening the pull request, make sure that your branch is up to date with the base branch.  
+
Run `git pull origin main` to confirm your branch is up to date.


.Steps

. Navigate to the GitHub repository that you want to create the pull request in. 
. Go to the *Pull requests* tab and select *New pull request*. 
 
. Identify the branches to compare and merge. 
+
Set the *base:* and *compare:* branches by selecting the branch name from the drop down list. 
+
[cols="1,1"]
|===
|*base:* 
|The branch that you want to merge your changes into. 
|*compare:*
|The branch that contains your changes.  

|===

. Optionally, perform a final check of your changes at this stage by scrolling to the end of the page to view the changed files. 

. Select *Open pull request* to begin building the pull request.   
+
The merge can begin after the pull request build completes, build times vary per repository. 
+
NOTE: You do not have to wait for the pull request to finish building to request a review. 

== Requesting a review
Assign a reviewer to the PR to request review and approval of the changed files. 

.Prerequisites

* The designated reviewer must have a GitHub user account, and the required permissions for the repository. 

.Steps

. Navigate to the repository that contains the pull request.
. Go to *Pull requests* tab and select the pull request that needs a reviewer.
* Under *Reviewers* on the right hand side of the screen, enter the GitHub username of the chosen reviewer into the textbox. If the reviewer has the correct permissions, their username should appear in the drop-down list. 

* Select the username in the dropdown list to assign the reviewer, a green tick appear next to the name when selected. 
+
Although the reviewer should get an email notfication of the request, you should let them know about that the review is requested in case the email is directed to their junk folder.
	
== Reviewing and approving PRs







