
= Getting started with GitHub pull request reviews
:toc: left
:toclevels: 3

:toc!:

[lead]
This foundational guide describes the steps to open a pull request and request a review of changed files using the GitHub UI.  

== Introduction to GitHub pull request reviews

A GitHub pull request is a request to merge changes from one branch into another branch. A successful pull request build verifies that the branches are compatible for merging.  

By default, any GitHub user with read access can review and request changes on open pull requests. However, organizations and repository administrators can limit and control who can request changes on open pull requests. Refer to your organization or repository adminstrator for guidance on specific questions about your repository settings. 

If you want a specific GitHub user or group to review, you can use the steps in this document to assign them to the pull request.   

link:https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews[Learn more about pull request reviews^].

== Opening a pull request

Before you can assign a reviewer, you must open a pull request between the branch that contains the changed files and the branch that you want your changes to be merged with. 

.Prerequisites

* You must have the required permissions to open a pull request in the chosen repository. 
* You must know the name of the branch that you want to merge your changes into. 


.Steps 

. Navigate to the GitHub repository for your branch. 

. Go to the *Pull requests* tab and select *New pull request*. 
 
. Identify the branches that you want to merge. 
+
Set the *base:* and *compare:* branches by selecting the branch name from the drop-down list. 
+
[%header,cols="1,1"]
|===
| Branch  | Selection
|*base:* 
|The branch that you want to merge your changes into. 
|*compare:*
|The branch that contains your changes.  

|===
+
IMPORTANT: You must make sure that you select the correct branch names. 

. At this stage, perform a final check of your changes by scrolling to the end of the page to view the changed files. 
+ 
* Additions are in green. 
+
* Deletions are in red.

. Select *Open pull request* to begin building the pull request.     
+
NOTE: Pull request build times vary depending on the repository. You do not have to wait for the pull request to finish building to request a review.  

== Requesting a review

Assign a GitHub user or group to the pull request to request review and approval of the changed files. You can assign any GitHub user or group that has the required repository permissions. 

When a pull request is opened, any GitHub user with the required repository permissions can review the pull request. This procedure details the steps to request a review from a specific GitHub user or group. 

.Prerequisites

* The designated reviewer or group must have a GitHub account and the required permissions for the repository. 
* You can only assign a reviewer after the pull request is opened. 


.Steps

. Navigate to the repository that contains the pull request. 

. Go to the *Pull requests* tab and select the pull request that requires a review.
. Assign the pull request.
+
Under *Reviewers* on the right side of the screen, enter the GitHub user or group name into the text box. 
+
If the reviewer has the correct permissions, the user or group name should appear in the drop-down list. 
+
NOTE: A green tick should appear next to the name on the list after it has been selected. 
+
If necessary, you can assign multiple users or groups to a pull request.

. Confirm that the reviewer received your request. 
+
Although reviewers automatically recieve an email notfiying them of the request, you should confirm that they are aware of the requested review. 
	








