
= Getting started with GitHub pull request reviews
:toc: left
:toclevels: 3

:toc!:

[lead]
This beginners guide describes the steps to open a pull request and requiest a review using the GitHub GUI.  

== Introduction to GitHub pull requests

To request a review of your files, open a pull request and assign the GitHub user who needs to approve the changes. 

== Opening a PR

Before you can assign a reviewer, you must open a pull request for the branch that contains the changed files against the branch that you want your changes to be merged with. 

.Prerequisites

* You must have the required permissions to open a pull request in the chosen repository. 
* You must know the name of the branch that you want to merge your changes into. 
* Your branch must be up to date with the base branch to avoid merge conflicts. Learn more about merge conflicts. 


.Steps 

. Navigate to the GitHub repository that you want to create the pull request in. 
. Go to the *Pull requests* tab and select *New pull request*. 
 
. Identify the branches to compare and merge. 
+
Set the *base:* and *compare:* branches by selecting the branch name from the drop-down list. 
+
[cols="1,1"]
|===
|*base:* 
|The branch that you want to merge your changes into. 
|*compare:*
|The branch that contains your changes.  

|===

. Optionally, perform a final check of your changes at this stage by scrolling to the end of the page to view the changed files. 
+ 
New text is displayed in green. Removed text is displayed in red.

. Select *Open pull request* to begin building the pull request.   
+
The merge can begin after the pull request build completes, build times vary depending on repository. 
+
NOTE: You do not have to wait for the pull request to finish building to request a review.  

== Requesting a review
Assign a reviewer to the pull request to request review and approval of the changed files. 

.Prerequisites

* The designated reviewer must have a GitHub user account, and the required permissions for the repository. 

.Steps

. Navigate to the repository that contains the pull request.
. Go to *Pull requests* tab and select the pull request that needs a reviewer.
. Assign the pull request.
+
.. Under *Reviewers* on the right hand side of the screen, enter the GitHub username of the chosen reviewer into the textbox. 
+
If the reviewer has the correct permissions, their username should appear in the drop-down list. 
+
.. Select the username in the drop-down list to assign the reviewer, a green tick appear next to the name when selected. 
+
Although the reviewer should get an email notfication of the request, you should confirm that they received the request. 
	








